<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-16 10:28

import datetime
from django.db import migrations, models
=======
# Generated by Django 4.0.3 on 2022-03-16 16:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> a113455dc421ba8539b68e5bb3b375a3f71f629a
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('otp', models.CharField(max_length=6, verbose_name=' Verification Code ')),
<<<<<<< HEAD
                ('valid_until', models.DateTimeField(default=datetime.datetime(2022, 3, 16, 10, 33, 8, 352509, tzinfo=utc), help_text='The timestamp of the moment of expiry of the saved token.')),
=======
                ('valid_until', models.DateTimeField(default=datetime.datetime(2022, 3, 16, 16, 24, 53, 715042, tzinfo=utc), help_text='The timestamp of the moment of expiry of the saved token.')),
>>>>>>> a113455dc421ba8539b68e5bb3b375a3f71f629a
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('phone', models.BigIntegerField(null=True, unique=True, verbose_name='Contact Number')),
                ('user_category', models.CharField(choices=[('Customer', 'Customer'), ('Staff', 'Staff'), ('Delivery', 'Delivery')], default='Customer', max_length=200, verbose_name='User Category')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('gender', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gender')),
                ('food_preference', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg'), ('Vegan', 'Vegan'), ('Eggetarian', 'Eggetarian'), ('Jain', 'Jain'), ('Normal', 'Normal')], default='Normal', max_length=200, verbose_name='Food Preference')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
>>>>>>> a113455dc421ba8539b68e5bb3b375a3f71f629a
    ]
