# Generated by Django 4.0.3 on 2022-03-16 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField()),
                ('otp', models.CharField(max_length=6, verbose_name=' Verification Code ')),
                ('valid_until', models.DateTimeField(default=datetime.datetime(2022, 3, 16, 10, 33, 8, 352509, tzinfo=utc), help_text='The timestamp of the moment of expiry of the saved token.')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('phone', models.BigIntegerField(null=True, unique=True, verbose_name='Contact Number')),
                ('user_category', models.CharField(choices=[('Customer', 'Customer'), ('Staff', 'Staff'), ('Delivery', 'Delivery')], default='Customer', max_length=200, verbose_name='User Category')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
