# Generated by Django 4.0.3 on 2022-03-27 21:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='food_preference',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg'), ('Normal', 'Normal')], default='Normal', max_length=200, verbose_name='Food Preference'),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 21, 4, 50, 153113, tzinfo=utc), help_text='The timestamp of the moment of expiry of the saved token.'),
        ),
    ]
