# Generated by Django 4.0.3 on 2022-03-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0002_myuser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.BigIntegerField()),
                ('otp', models.CharField(max_length=6, verbose_name=' Verification Code ')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name=' Generation time ')),
            ],
        ),
    ]
