# Generated by Django 4.0.3 on 2022-03-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0002_myuser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
