# Generated by Django 4.0.3 on 2022-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0003_remove_myuser_current_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Contact Number'),
        ),
    ]
