# Generated by Django 4.0.3 on 2022-03-16 10:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0004_alter_otpmodel_valid_until_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 10, 49, 31, 315966, tzinfo=utc), help_text='The timestamp of the moment of expiry of the saved token.'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('gender', models.CharField(blank=True, max_length=200, null=True, verbose_name='Gender')),
                ('food_preference', models.CharField(choices=[('Veg', 'Veg'), ('Non Veg', 'Non Veg'), ('Vegan', 'Vegan'), ('Eggetarian', 'Eggetarian'), ('Jain', 'Jain'), ('Normal', 'Normal')], default='Normal', max_length=200, verbose_name='Food Preference')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
