# Generated by Django 4.0.3 on 2022-03-12 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0003_otpmodel'),
        ('UsersApi', '0004_remove_myuser_id_alter_myuser_phone'),
    ]

    operations = [
    ]
