# Generated by Django 4.0.3 on 2022-03-12 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0005_merge_20220312_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='otpmodel',
            name='time',
        ),
        migrations.AddField(
            model_name='otpmodel',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 9, 33, 38, 94115, tzinfo=utc), help_text='The timestamp of the moment of expiry of the saved token.'),
        ),
    ]
