# Generated by Django 4.0.3 on 2022-03-12 10:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0006_rename_phone_number_otpmodel_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 10, 23, 17, 147894, tzinfo=utc), help_text='The timestamp of the moment of expiry of the saved token.'),
        ),
    ]
