# Generated by Django 4.0.3 on 2022-03-12 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0008_alter_otpmodel_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 11, 44, 22, 565161, tzinfo=utc), help_text='The timestamp of the moment of expiry of the saved token.'),
        ),
    ]
