# Generated by Django 4.0.3 on 2022-03-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0003_otp'),
        ('UsersApi', '0011_alter_otpmodel_valid_until'),
    ]

    operations = [
    ]
