# Generated by Django 4.0.3 on 2022-03-13 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApi', '0012_merge_0003_otp_0011_alter_otpmodel_valid_until'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 5, 42, 8, 302045, tzinfo=utc), help_text='The timestamp of the moment of expiry of the saved token.'),
        ),
    ]
